baseURL: devSpec.h0p1.com/
title: Development specification
enableRobotsTXT: true
theme:
  - doscy
enableGitInfo: true
contentDir: content/zh
defaultContentLanguage: zh
defaultContentLanguageInSubdir: false
enableMissingTranslationPlaceholders: true
disableKinds:
  - taxonomy
  - taxonomyTerm
pygmentsCodeFences: true
pygmentsUseClasses: false
pygmentsUseClassic: false
pygmentsStyle: tango
permalinks:
  blog: '/:section/:year/:month/:day/:slug/'
outputs:
  section:
    - HTML
    - RSS
    - print
blackfriday:
  plainIDAnchors: true
  hrefTargetBlank: true
  angledQuotes: false
  latexDashes: true
imaging:
  resampleFilter: CatmullRom
  quality: 75
  anchor: smart
services:
  googleAnalytics:
    id: UA-00000000-0
languages:
  zh:
    title: 开发规范
    description: 一个最佳实践的开发规范和配套工具集合。
    languageName: 中文
    contentDir: content/zh
    weight: 1
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: tango
params:
  copyright: TaibiaoGuo
  privacy_policy: 'https://policies.google.com/privacy'
  version_menu: Releases
  archived_version: false
  version: '0.0'
  url_latest_version: 'https://example.com'
  github_repo: "https://github.com/TaibiaoGuo/devSpec"
  github_project_repo: "https://github.com/TaibiaoGuo/devSpec/projects"
  github_subdir:
  time_format_blog: 'Monday, January 02, 2006'
  time_format_default: 'January 2, 2006'
  rss_sections:
    - blog
  gcs_engine_id: '011217106833237091527:la2vtv2emlw'
  algolia_docsearch: false
  offlineSearch: false
  offlineSearchSummaryLength: 70
  offlineSearchMaxResults: 10
  prism_syntax_highlighting: false
  ui:
    sidebar_menu_compact: false
    breadcrumb_disable: false
    sidebar_search_disable: false
    navbar_logo: true
    feedback:
      enable: true
      'yes': >-
        Glad to hear it! Please <a
        href="https://github.com/TaibiaoGuo/devSpec/discussions/new">tell us how we can
        improve</a>.
      'no': >-
        Sorry to hear that. Please <a
        href="https://github.com/TaibiaoGuo/devSpec/discussions/new">tell us how we can
        improve</a>.
    readingtime:
      enable: false
  links:
    developer:
      - name: GitHub
        url: 'https://github.com/TaibiaoGuo/devSpec'
        icon: fab fa-github
        desc: Development takes place here!
  mermaid:
    enable: true
    theme: default
  plantuml:
    enable: true
    theme: default
    svg_image_url: 'https://www.plantuml.com/plantuml/svg/'
  katex:
    enable: true
    html_dom_element: document.body
    options:
      delimiters:
        - left:  $$
          right: $$
          display: true
        - left: $
          right: $
          display: false

  print:
    disable_toc: false
